/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define HAVE_BYTESWAP_H 1
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define CONFIG_OSS 1
#define CONFIG_VNC_TLS 1
#define QEMU_VERSION "0.9.1"
#define TEMU_HOME "/home/hhui/Experiments/backup/BitBlaze/Total_Components/temu-1.0"
#define PROJECT_HOME "/home/hhui/Experiments/backup/BitBlaze/Total_Components/temu-1.0/sample_plugin"
#define TAINT_ENABLED 1
#define DEFINE_BLOCK_BEGIN
#define DEFINE_INSN_BEGIN
#define DEFINE_INSN_END
#define DEFINE_EIP_TAINTED
#define MEM_CHECK
#define REG_CHECK
#define NO_PROPAGATE
#define CALLSTRING_ANALYSIS
#define TAINT_FLAGS 1
#define PRECISE_EFLAGS
#define PLUGIN_SAMPLE
#define CONFIG_SDL 1
#define CONFIG_UNAME_RELEASE ""
