VEX_DIR=/home/hhui/Experiments/BitBlaze/Total_Components/vine-1.0/VEX/
LIBASMIR_CXXFLAGS=-I/home/hhui/Experiments/BitBlaze/Total_Components/vine-1.0/VEX//pub -I/home/hhui/Experiments/BitBlaze/Total_Components/vine-1.0/src/include -g -O2
LIBASMIR_LDFLAGS=-L/home/hhui/Experiments/BitBlaze/Total_Components/vine-1.0/VEX/ -L/home/hhui/Experiments/BitBlaze/Total_Components/vine-1.0/src 
LIBASMIR_LIBS=-lasmir -lvex -lbfd -liberty
